### PR TITLE
Update grammar to vyper 0.3.10

### LINKED ISSUE #14: Update to support Vyper 0.3.10
Some outdated features:
- Constants for types _MAX and _EMPTY are replaced by builtin function calls
  - For example, `UINT_MAX` is now `max(uint256)` and `EMPTY_ADDRESS` is now `empty(address)`
- Ternary expressions are not supported
- Multi-line comments are not parsed properly
- DynArray is not supported
- constant/immutable are not fully supported
- old keywords such as `modifying` do not exist anymore

### PR DESCRIPTION
**Pull request by DanielSchiavini**
Fixes #14 and #18

- Add build and test workflow based on the [intellij plugin template](https://github.com/JetBrains/intellij-platform-plugin-template)
  - Test runs are [running in my fork](https://github.com/DanielSchiavini/vyper-plugin/actions) already
- Run tests based on the existing examples
  - Add complex Curve contract for a more complex example testing the grammar
  - In the future, we should have a lot more negative tests too
- Add kover plugin to check the coverage
- Updated the grammar to vyper 0.3.0 (see [vyper.bnf](https://github.com/NikitaMishin/vyper-plugin/pull/19/files#diff-c2cceb02381a16c6506f332351a00718f4275abb9ecf32d5d283e8b6d4dc49f7))
  - Fixed some older issues e.g. `\` and multiline strings (e.g. docstrings) not being supported
  - Ternary expressions (`x if y else z`)
  - Remove `map` in favor of `HashMap`
  - Remove `wei_value`, `timestamp`, `timedelta` in favor of `uint256`
  - Remove `contract` keyword in favor of `interface`
  - New `BytesM` and `IntM` types
  - Removed `units` statement
  - Add support for trailing commas
  - Updates to the range statement
- Update file and plugin icons
- Update documentation

Unfortunately, generated files are being committed. I tried to generate them at build time but that does not support mixins.

### CODE REVIEW

**Comment by DanielSchiavini** [comment]
@NikitaMishin Do you want to have a look at this PR?

**Comment by NikitaMishin** [comment]
> @NikitaMishin Do you want to have a look at this PR?

yep will look in a tad

**Review by NikitaMishin — APPROVED** [review]
Looks good, huge thumbs up!

So, right now, is the grammar more or less stable and no breaking changes in Vyper expected?

**Comment by DanielSchiavini** [comment]
:laughing: unfortunately not, there are a breaking changes expected in 0.4.0 which will release soon.
There will be new syntax for modules and a few other changes. I'll fix those in #15 and find a way to support 0.3 and 0.4 next to each other.

**Pull request merged**
